/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.ControlRelatorio;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Animal;
import model.Funcionario;
import model.Pessoa;

/**
 *
 * @author Admin
 */
public class TelaRelatori extends javax.swing.JFrame {

    private ControlRelatorio control;
    private SimpleDateFormat dateFormat;
    public TelaRelatori() {
        initComponents();
         control = new ControlRelatorio();
        dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        configurarComponentes();
        carregarDadosExemplo();
    }

    private void configurarComponentes() {
        // Configurar ComboBox
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Animais");
        jComboBox1.addItem("Pessoas");
        jComboBox1.addItem("Funcionários");
        jComboBox1.addItem("Todos");
        
        // Configurar área de texto
        jTextArea1.setFont(new Font("Consolas", Font.PLAIN, 12));
        
        // Configurar label de estatísticas
        jLabel1.setText("Selecione o tipo de relatório e clique em Gerar");
        atualizarEstatisticas();
    }
    
     private void carregarDadosExemplo() {
        // Adiciona alguns dados de exemplo se estiver vazio
        if (control.getQuantidadeAnimais() == 0) {
            control.adicionarAnimal(new Animal("Rex", "Cachorro", 3));
            control.adicionarAnimal(new Animal("Mimi", "Gato", 2));
            control.adicionarAnimal(new Animal("Piu", "Pássaro", 1));
            control.adicionarAnimal(new Animal("Bobby", "Cachorro", 5));
        }
        
        if (control.getQuantidadePessoas() == 0) {
            control.adicionarPessoa(new Pessoa("João Silva", "joao@email.com", "841234567"));
            control.adicionarPessoa(new Pessoa("Maria Santos", "maria@email.com", "842345678"));
            control.adicionarPessoa(new Pessoa("Carlos Lima", "carlos@email.com", "843456789"));
        }
        
        if (control.getQuantidadeFuncionarios() == 0) {
            control.adicionarFuncionario(new Funcionario("Ana Costa", "Gerente", 35000));
            control.adicionarFuncionario(new Funcionario("Pedro Alves", "Analista", 25000));
            control.adicionarFuncionario(new Funcionario("Sofia Mendes", "Assistente", 18000));
            control.adicionarFuncionario(new Funcionario("Miguel Santos", "Coordenador", 28000));
        }
    }
    
        private void atualizarEstatisticas() {
        jLabel1.setText(
            "Estatísticas: " +
            "Animais: " + control.getQuantidadeAnimais() + " | " +
            "Pessoas: " + control.getQuantidadePessoas() + " | " +
            "Funcionários: " + control.getQuantidadeFuncionarios() + " | " +
            "Total: " + control.getQuantidadeTotal() + " registros"
        );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setForeground(new java.awt.Color(255, 204, 153));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Gerar Relatorio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tipo de Relatorio");

        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Exportar para txt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 29, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String tipo = (String) jComboBox1.getSelectedItem();
        
        // Cabeçalho do relatório
        String cabecalho = "═".repeat(60) + "\n" +
                          "           RELATÓRIO AUTOMÁTICO\n" +
                          "═".repeat(60) + "\n" +
                          "Tipo: " + tipo + "\n" +
                          "Data: " + dateFormat.format(new Date()) + "\n" +
                          "─".repeat(60) + "\n\n";
        
        // Gera o relatório usando RECURSIVIDADE
        String relatorio = control.gerarRelatorioRecursivo(tipo, 0);
        
        // Rodapé
        String rodape = "\n" + "─".repeat(60) + "\n" +
                       "Relatório gerado automaticamente com recursividade\n" +
                       "═".repeat(60);
        
        // Exibe o relatório completo
        jTextArea1.setText(cabecalho + relatorio + rodape);
        
        JOptionPane.showMessageDialog(this, 
            "✅ Relatório gerado com RECURSIVIDADE!\n" +
            "📊 Tipo: " + tipo + "\n" +
            "📝 Itens listados: " + contarItens(relatorio));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String conteudo = jTextArea1.getText();
        if (conteudo.trim().isEmpty() || conteudo.contains("Selecione o tipo")) {
            JOptionPane.showMessageDialog(this, "Gere um relatório primeiro!");
            return;
        }
        
        String nomeArquivo = "relatorio_" + new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date()) + ".txt";
        control.exportarRelatorio(conteudo, nomeArquivo);
        
        JOptionPane.showMessageDialog(this, 
            "📁 Relatório exportado com sucesso!\n" +
            "💾 Arquivo: " + nomeArquivo);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jTextArea1.setText("");
        jLabel1.setText("Selecione o tipo de relatório e clique em Gerar");
    }//GEN-LAST:event_jButton3ActionPerformed

        private int contarItens(String texto) {
        if (texto == null || texto.isEmpty()) return 0;
        // Conta as linhas que começam com "•" (itens da lista)
        int count = 0;
        for (String linha : texto.split("\n")) {
            if (linha.trim().startsWith("•")) {
                count++;
            }
        }
        return count;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
