package view;


import control.ControlPagamento;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Freelancer;
import model.Funcionario;
import model.Pagavel;


/**
 *
 * @author Admin
 */
public class TelaPagamento extends javax.swing.JFrame {

      private ControlPagamento control;
    private DefaultTableModel tableModel;
    public TelaPagamento() {
        initComponents();
        control = new ControlPagamento();
        configurarComponentes();
        atualizarTabela();
    }

 private void configurarComponentes() {
        // Configurar ComboBox
        jComboBox1Funcionario.removeAllItems();
        jComboBox1Funcionario.addItem("Funcionário");
        jComboBox1Funcionario.addItem("Freelancer");
        
        // Configurar tabela
        configurarTabela();
        
        // Configurar labels
        lbTotal.setText("Total de Registros: 0");
        lblTotalPago.setText("Total a Pagar: 0,00 MT");
        lblTotalPago.setForeground(Color.BLUE);
        
        // Configurar campos iniciais
        atualizarCamposPorTipo();
    }
    
     private void configurarTabela() {
        tableModel = new DefaultTableModel(
            new Object[][]{}, 
            new String[]{"Tipo", "Nome", "Detalhes", "Pagamento"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable.setModel(tableModel);
    }
    
     private void atualizarTabela() {
        // Limpa a tabela
        tableModel.setRowCount(0);
        
        // Preenche com os dados usando polimorfismo
        for (Pagavel pagavel : control.getPagaveis()) {
            if (pagavel instanceof Funcionario) {
                Funcionario func = (Funcionario) pagavel;
                tableModel.addRow(new Object[]{
                    "Funcionário",
                    func.getNome(),
                    "Salário Fixo: " + String.format("%.2f", func.getSalarioFixo()) + " MT",
                    String.format("%.2f", func.calcularPagamento()) + " MT"
                });
            } else if (pagavel instanceof Freelancer) {
                Freelancer free = (Freelancer) pagavel;
                tableModel.addRow(new Object[]{
                    "Freelancer", 
                    free.getNome(), 
                    free.getHorasTrabalhadas() + "h @ " + 
                    String.format("%.2f", free.getValorHora()) + " MT/h",
                    String.format("%.2f", free.calcularPagamento()) + " MT"
                });
            }
        }
        
        // Atualiza contador
        lbTotal.setText("Total: " + control.getQuantidadePagaveis() + " registros");
    }
     
      private void atualizarCamposPorTipo() {
        String tipo = (String) jComboBox1Funcionario.getSelectedItem();
        if ("Funcionário".equals(tipo)) {
            jLabel3.setText("Salário Fixo (MT):");
            jLabel5.setText("---");
            jTextField2.setEnabled(false);
            jTextField2.setBackground(Color.LIGHT_GRAY);
            jTextField2.setText("");
            txtValorPorHora.setText("");
        } else {
            jLabel3.setText("Valor por Hora (MT):");
            jLabel5.setText("Horas Trabalhadas:");
            jTextField2.setEnabled(true);
            jTextField2.setBackground(Color.WHITE);
            txtValorPorHora.setText("");
        }
    }
    
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        jComboBox1Funcionario = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTotalPago = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        txtValorPorHora = new javax.swing.JTextField();
        btnListar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jTable.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipo", "Nome", "Detalhes", "Pagamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setResizable(false);
            jTable.getColumnModel().getColumn(1).setResizable(false);
            jTable.getColumnModel().getColumn(2).setResizable(false);
            jTable.getColumnModel().getColumn(3).setResizable(false);
        }

        txtNome.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setText("Nome");

        btnCadastrar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jComboBox1Funcionario.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jComboBox1Funcionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setText("Tipo");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setText("Valor por hora");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setText("Horas trabalhadas");

        lblTotalPago.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        lbTotal.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        txtValorPorHora.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        btnListar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCalcular.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcular))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1Funcionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNome)
                            .addComponent(txtValorPorHora)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSair)
                            .addComponent(btnEliminar)
                            .addComponent(btnListar)
                            .addComponent(btnCadastrar))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCadastrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnListar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEliminar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addGap(37, 37, 37)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSair)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBox1Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32))
                                    .addComponent(txtValorPorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(93, 93, 93)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalPago, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcular))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

         try {
            String nome = txtNome.getText().trim();
            String tipo = (String) jComboBox1Funcionario.getSelectedItem();
            String valorStr = txtValorPorHora.getText().trim();
            
            // Validações básicas
            if (nome.isEmpty() || valorStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha nome e valor!");
                return;
            }
            
            double valor = Double.parseDouble(valorStr);
            Pagavel pagavel;
            
            if ("Funcionário".equals(tipo)) {
                pagavel = new Funcionario(nome, valor);
            } else {
                String horasStr = jTextField2.getText().trim();
                if (horasStr.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Para freelancer, preencha as horas trabalhadas!");
                    return;
                }
                int horas = Integer.parseInt(horasStr);
                pagavel = new Freelancer(nome, valor, horas);
            }
            
            control.cadastrarPagavel(pagavel);
            JOptionPane.showMessageDialog(this, tipo + " cadastrado com sucesso!");
            
            limparCampos();
            atualizarTabela();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Valores numéricos devem ser números válidos!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
  control.carregarDados();
        atualizarTabela();
        JOptionPane.showMessageDialog(this, 
            "Dados carregados!\nTotal: " + control.getQuantidadePagaveis() + " registros");
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       int linhaSelecionada = jTable.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para eliminar!");
            return;
        }
        
        String nome = (String) jTable.getValueAt(linhaSelecionada, 1);
        int confirmacao = JOptionPane.showConfirmDialog(this, 
            "Deseja eliminar: " + nome + "?", 
            "Confirmar Eliminação", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirmacao == JOptionPane.YES_OPTION) {
            control.getPagaveis().remove(linhaSelecionada);
            control.salvarDados();
            JOptionPane.showMessageDialog(this, "Registro eliminado com sucesso!");
            atualizarTabela();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
         // Usa POLIMORFISMO para calcular todos os pagamentos
        double total = control.calcularTotalPagamentos();
        double totalRecursivo = control.calcularTotalRecursivo(0); // Versão recursiva
        
        int funcionarios = control.contarPorTipo("Funcionário");
        int freelancers = control.contarPorTipo("Freelancer");
        
        lblTotalPago.setText("Total a Pagar: " + String.format("%.2f", total) + " MT");
        
        JOptionPane.showMessageDialog(this,
            "Cálculo realizado com POLIMORFISMO!\n\n" +
            "Funcionários: " + funcionarios + "\n" +
            "Freelancers: " + freelancers + "\n" +
            "Total a pagar: " + String.format("%.2f", total) + " MT\n" +
            "(Recursivo: " + String.format("%.2f", totalRecursivo) + " MT)");
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
         control.salvarDados();
        JOptionPane.showMessageDialog(this, "Dados salvos! Saindo...");
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

       private void jComboBox1FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        atualizarCamposPorTipo();
    }                                                     

         private void limparCampos() {
        txtNome.setText("");
        txtValorPorHora.setText("");
        jTextField2.setText("");
        txtNome.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> jComboBox1Funcionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lblTotalPago;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtValorPorHora;
    // End of variables declaration//GEN-END:variables
}
